FROM quay.io/konflux-ci/yq:latest as yq

FROM quay.io/fedora/fedora:40

COPY --from=yq /usr/bin/yq /usr/bin/yq

RUN dnf -y install tox git; dnf clean all

LABEL name="konflux-release-data-ci" \
    version="0.1" \
    release="1" \
    summary="Container image for running gitlab ci tasks for konflux-release-data config repo" \
    com.redhat.component="konflux-release-data-ci" \
    description="see summary :D" \
    distribution-scope="restricted" \
    url="https://github.com/release-engineering/konflux-release-data-ci/tree/main" \
    vendor="Red Hat, Inc." \
    io.k8s.display-name="konflux-release-data-ci" \
    io.k8s.description="Container image for running gitlab ci tasks for konflux-release-data config repo" \
    io.openshift.tags="oci"

ENTRYPOINT []


